sudo: false
language: node_js
node_js: "node"

script: ""

before_deploy:
  - npm install firebase-tools

deploy:
  skip_cleanup: true
  provider: script
  script:
    - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master

cache:
  directories:
    - node_modules
